eureka:
  client:
    fetch-registry: 'false'
    # we don't want this server to register this server with itself
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import: 'optional:configserver:http://localhost:8888'
  application:
    name: naming-server

server:
  port: '8761'
